### PR TITLE
Simple error handler

### PR DESCRIPTION
**Pull request by bralbral**
Simple error handler

### CODE REVIEW

**Comment by rhamza783** [comment]
Hi i m hamza i need your help how can i connect you

**Comment by rhamza783** [comment]
I tired to find you on social media but can't find ur account if u feel free please reply

**Comment by bralbral** [comment]
> I tired to find you on social media but can't find ur account if u feel free please reply

just give me your contacts

**Comment by rhamza783** [comment]
Telegram: https://t.me/HA_YS_2_899

**Pull request merged**
